# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import csv
import os
import json
import sys
import time


class DigFileFromPath(object):
    def __init__(self, dic):
        self.selectPath = dic['检索目录']
        self.savePath = dic['保存目录']
        self.bdName = dic['营业部名称']

    def exportFile(self):
        if os.path.isdir(self.selectPath):
            self.fileList = []
            for root, dirs, files in os.walk(self.selectPath):
                for file in files:
                    self.fileList.append(file)
        else:
            print('请检查检索目录是否正确')
            print('程序3秒后退出')
            time.sleep(3)
            sys.exit(-1)
        if os.path.isdir(self.savePath):
            if self.bdName:
                with open(self.savePath + '\\检索结果_' + self.bdName + '.csv', 'w', newline='') as f:
                    writer = csv.writer(f, dialect='excel')
                    for i in self.fileList:
                        writer.writerow([i])
            else:
                print('请配置营业部名称')
                print('程序3秒后退出')
                time.sleep(3)
                sys.exit(-1)
        else:
            print('请检查保存目录是否正确')
            print('程序3秒后退出')
            time.sleep(3)
            sys.exit(-1)


if __name__ == '__main__':
    try:
        print('开始检查配置文件')
        config_path = os.getcwd()
        with open(config_path + '\\pathEdit.json', 'r', encoding='utf-8') as fp:
            json_data = json.load(fp)
        time.sleep(1)
        print('配置文件检索完毕')
        print('开始检索目录')
        digFile = DigFileFromPath(json_data)
        digFile.exportFile()
        time.sleep(1)
        print('目录检索完毕，文件已生成，请检查')
        time.sleep(1)
        print('程序3秒后退出')
        time.sleep(3)
        sys.exit(0)
    except Exception as e:
        print('请检查pathEdit.json文件是否跟程序在同一目录')
        print('程序3秒后退出')
        time.sleep(3)
        sys.exit(-1)

