# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import json
import sys
import time


class DigFileFromPath(object):
    def __init__(self, dic, config_path):
        self.filePath = dic['文件目录']
        self.format = str(dic['21还是22格式'])
        self.date = str(dic['日期'])
        self.path = config_path
        self.fileList = []

    def exploreFile(self):
        try:
            if os.path.isdir(self.filePath):
                for root, dirs, files in os.walk(self.filePath):
                    for file in files:
                        if str.upper(file.rsplit('_', 2)[-1]) == '04.TXT' and file.rsplit('_', 2)[-2] == self.date:
                            self.fileList.append(os.path.join(root, file))
        except Exception as e:
            print(e)
        # else:
        #     print('请检查目录是否配置正确')
        #     print('程序3秒后退出')
        #     time.sleep(3)
        #     sys.exit(-1)
        self.count21 = 0
        self.count22 = 0
        for file in self.fileList:
            print(file)
            with open(file, 'r') as f:
                interFace = str(f.readlines()[1])
                if self.format == '21' and '21' in interFace:
                    with open(self.path + '\\结果21_' + self.date + '.txt', 'a+') as ff:
                        ff.writelines(file + '\n')
                    self.count21 += 1

                elif self.format == '22' and '22' in interFace:
                    with open(self.path + '\\结果22_' + self.date + '.txt', 'a+') as ff:
                        ff.writelines(file + '\n')
                    self.count22 += 1

        if self.format == '21':
            print('总共有21文件 ' + str(self.count21) + ' 个')
        elif self.format == '22':
            print('总共有22文件 ' + str(self.count22) + ' 个')


if __name__ == '__main__':
    try:
        print('开始检查配置文件')
        config_path = os.getcwd()
        print('检索路径：' + config_path)
        with open(config_path + '\\editMe.json', 'r', encoding='utf-8') as fp:
            json_data = json.load(fp)
        time.sleep(1)
        print('配置文件检索完毕')
        print('开始检索目录')
        digFile = DigFileFromPath(json_data, config_path)
        digFile.exploreFile()
        time.sleep(1)
        print('目录检索完毕，结果已生成，请检查')
        time.sleep(1)
        print('程序3秒后退出')
        time.sleep(3)
        sys.exit(0)
    except Exception as e:
        print('请检查editMe.json文件是否跟程序在同一目录')
        print('程序3秒后退出')
        print(e)
        time.sleep(3)
        sys.exit(-1)
